### ISSUE TITLE
一笪血_跡_ zik6 is a typo, should be zik1

### ISSUE THREAD

**Issue by AlienKevin** [hon9kon9ize/yue-g2p-benchmark#2]
TLDR: 一笪血_跡_ zik6 is a typo from words.hk. Should be zik1.

Reference:
1. rime:
```
跡,zik1,預設,,,
跡,zek3,罕見,,,
```
2. jyut.net: zik1/zek3

**Comment by AlienKevin** [comment]
Another typo from words.hk:
```
推薦信 teoi1 zin3 syu1
```

**Comment by AlienKevin** [comment]
Three more typos that are fixed in newer versions of workds.hk.
```
文▁人▁雅士 man4 jun4 ngaa5 si6
綠_化_都市 luk6 faa1 dou1 si5 
從大▁處▁着眼 guk6
```

**Comment by AlienKevin** [comment]
Above are the errors I found but there are probably more. I think it would be best to manually check the wordshk pronunciations. When you automatically mine characters with different pronunciation, chances are those are typos, not actual alternative pronuncations.

**Comment by indiejoseph** [comment]
Thanks for your reporting, I will fix it ASAP
