### ISSUE TITLE
Penalized for alternative pronunciations

### ISSUE THREAD

**Issue by AlienKevin** [hon9kon9ize/yue-g2p-benchmark#3]
According to wordshk, both pronuncations of the underlined characters are acceptable. However, one of them is set as the standard answer and the other pronunciation gets penalized.
1. 偷睇考_試_卷 | tau1 tai2 haau2 si5 gyun2 | si5/si3
2. 拎出_嚟_ | ling1 ceot1 lai4 | lai4/lei4
3. 一碗燒_鵝_瀨粉 | jat1 wun2 siu1 ngo2 laai6 fan2 | ngo2/ngo4
4. 開正我嗰_瓣_ | hoi1 zeng3 ngo5 go2 faan6 | faan6/faan2/baan6
5. 模_擬_考試 | mou4 ji5 haau2 si5 | ji5/ji4
6. 睇_吓_ | tai2 haa2 | haa2/haa5
7. 出版社聯_絡_資料 | ceot1 baan2 se5 lyun4 lok3 zi1 liu6 | lok3/lok6
8. _啜_手指 | zyut3 sau2 zi2 | zyut3/zyut1
9. 勞資_糾_紛 | lou4 zi1 gau2 fan1 | gau2/dau2
10. 美國駐香港大_使_館 | mei5 gwok3 zyu3 hoeng1 gong2 daai6 si3 gun2 | si3/si5
11. 親愛嘅_媽_媽 | can1 oi3 ge3 maa1 maa1 | maa1/maa4
12. 鬼佬_鴛_鴦 | gwai2 lou2 jyun1 joeng1 | jyun1/jin1
13. 捍衞學術自由 | hon5 wai6 hok6 seot6 zi6 jau4 | hon5/hon2

The above are just a few examples I noticed. There are probably more. I recommend writing an algorithm to check for such variants and manually check the sentence if there are ambiguities.

**Comment by indiejoseph** [comment]
Thanks for reporting, will check it, we should modify the coding to accept multiple standard answer, and what do you mean check the ambiguities? assuming if the label is correct.

**Comment by AlienKevin** [comment]
By ambiguity I meant multiple standard answers. Wordshk actually lists multiple pronunciation for some phrases so they can be quickly used to identify potential cases with multiple stnadard answers.

**Comment by graphemecluster** [comment]
- 3 真係有人讀 ngo4？同埋實在太多燒鵝喇，三行我 delete 咗兩行
- 4 真係有人讀 faan2？係範疇嘅意思喎
- 6 我覺得係 ambiguous，所以我改咗句句子
- 11 我覺得因為有個「嘅」字所以唔會噉讀，如果係「親愛的媽媽」就唔同

**Comment by AlienKevin** [comment]
Thanks for reviewing them. I proposed the list of ambiguous candidates based purely on the alternative pronunciations in words.hk. There can be cases where one pronunciation makes more sense under a given context, so human review is very much needed.

**Comment by indiejoseph** [comment]
@Naozumi520 is helped on reviewing the words.hk data, and he will create a PR soon
